### ISSUE TITLE
some problems about make_labels and visualization

### ISSUE THREAD

**Issue by linxind** [ybarancan/BEV_feat_stitch#11]
hi, after i runned `make_nuscenes_labels.py` on nuscenes-v1.0-mini with `Map expansion pack (v1.3)` ,  the result is like this:

![885472e412f4499cacf2f4796c309276](https://user-images.githubusercontent.com/17938759/166465325-213b571b-4a06-46e0-a16a-e2c61f3e652f.png)

there are some artifacts (white lines on the upper right corner), did I miss anything? I only changed `dataroot` and `output_root`.
And there doesn't seem to be any cars in the figure, I don't know if it is related to v1.3 Map expansion pack.

Besides, how to change binary_labels to rgb figure shown in the paper?

![QQ截图20220503215613](https://user-images.githubusercontent.com/17938759/166466773-6b0f3df5-4ecc-4e7f-bb9b-5e8485882981.jpg)

Thanks a lot.

**Comment by ybarancan** [comment]
Hi,
The labels are encoded. So if you visualize the raw saved png file, it won't make much sense. Try visualizing the decoded versions. Then, if there are sill artifacts on the class labels, we can discuss further. 
The previous commit had the code for producing the figures in the paper. However, its assumptions about the data caused some problems. You can check the code snippet in the previous commit and use it as a template. 
Best

**Comment by linxind** [comment]
Thank you for your generous reply!  I have successfully made the labels.

**Comment by Drchz155** [comment]
> 感谢您的慷慨回复！我已经成功地制作了标签。



> 感谢您的慷慨回复！我已经成功地制作了标签。

感谢您的评论，我也得到了如您效果类似的黑色图像，我该怎么解码可视化他，获得可以使用的标签，或者这些黑色图片本身就是可以使用的么？ 万分感谢 祝您生活愉快，万事顺利
