### ISSUE TITLE
make_nuscenes_label.py and make_argoverse_label.py failed

### ISSUE THREAD

**Issue by synsin0** [ybarancan/BEV_feat_stitch#4]
I like very much about your work of semantic feature extraction in BEV. However, I encountered several problem for reproducing your work. 
dataset_creator.py succeeds.
make_nuscenes_label.py failed. The error message is like:

======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 33.474 seconds.
======
Reverse indexing ...
Done reverse indexing in 3.7 seconds.
======

Generating labels...
ERROR:root:PROCESSING SCENE scene-0001
Traceback (most recent call last):
  File "make_nuscenes_labels.py", line 149, in <module>
    process_scene(nuscenes, map_data, scene, exp_config)
  File "make_nuscenes_labels.py", line 31, in process_scene
    process_sample(nuscenes, scene_map_data, sample, config)
  File "make_nuscenes_labels.py", line 47, in process_sample
    process_sample_data(nuscenes, map_data, sample_data, lidar_pcl, config)
  File "make_nuscenes_labels.py", line 57, in process_sample_data
    config.map_resolution)
  File "/home/yining/BEV_feat_stitch/dataset/nuscenes_utils.py", line 42, in get_map_masks
    resolution) for layer, polys in map_data.items()]
  File "/home/yining/BEV_feat_stitch/dataset/nuscenes_utils.py", line 42, in <listcomp>
    resolution) for layer, polys in map_data.items()]
  File "/home/yining/BEV_feat_stitch/dataset/nuscenes_utils.py", line 71, in get_layer_mask
    render_shapely_polygon(mask, polygon, extents, resolution)
  File "/home/yining/BEV_feat_stitch/dataset/nuscenes_utils.py", line 146, in render_shapely_polygon
    render_polygon(mask, polygon.exterior.coords, extents, resolution, 1)
  File "/home/yining/BEV_feat_stitch/dataset/utils.py", line 38, in render_polygon
    polygon = (polygon - np.array(extents[:2])) / resolution
ValueError: operands could not be broadcast together with shapes (0,) (2,) 

make_argoverse_label.py failed. The error message is like:

Loading Argoverse tracking data at /data/datasets/argoverse/argoverse-tracking/all/
ERROR:root:

==> Processing scene: 9407efb5-5a87-30a9-b5f7-b517242f5a37
Traceback (most recent call last):
  File "make_argoverse_labels.py", line 91, in <module>
    process_split(map_data, exp_config)
  File "make_argoverse_labels.py", line 36, in process_split
    process_scene( scene, map_data, config)
  File "make_argoverse_labels.py", line 47, in process_scene
    process_frame(scene, camera, frame, map_data, config)
  File "make_argoverse_labels.py", line 55, in process_frame
    config.map_resolution)
  File "/home/yining/BEV_feat_stitch/dataset/argoverse_utils.py", line 55, in get_object_masks
    for obj in scene.get_label_object(frame):
  File "/home/yining/BEV_feat_stitch/argoverse-api/argoverse/data_loading/argoverse_tracking_loader.py", line 563, in get_label_object
    return object_label.read_label(self._label_list[log_id][idx])
IndexError: list index out of range

The errors are located in basic utils so I hope for technical help, thanks.

**Comment by ybarancan** [comment]
Hi,
Thank you for your interest.  
Nuscenes error happens because some polygons are problematic. I added a try: except at the rendering part that ignores the problematic polygons. 

The Argoverse error stems from version difference. Please make sure you are using the new Argoverse (1.2) data files. 
Best

**Comment by synsin0** [comment]
Thanks for your timely patch, now I can successfully complete the preprocessing of the nuscenes dataset, but I still have a problem, the official website of argoverse https://www.argoverse.org/data.html only has 1.0 (deprecated) and 1.1 version, please help how and where to download version 1.2, or are you talking about the argoverse_2 dataset?

**Comment by ybarancan** [comment]
Yes, sorry  I meant argoverse_2.

**Comment by synsin0** [comment]
Is Argoverse 2 published or not? Could you please attach the website url? Another question regarding model is that the from deeplab import model. Which deeplab is your requirement?

**Comment by ybarancan** [comment]
https://www.argoverse.org/data.html Should be Argoverse 1.1 .  You can check if it is the correct one by making sure that 9407efb5-5a87-30a9-b5f7-b517242f5a37 doesn't exist. 
The deeplab is the deeplab from tensorflow/models/research. You can clone/download https://github.com/tensorflow/models/tree/master/research . On top of the files in this project you will see that they are added to path with 'sys.path.append'. You can modify the path to point to the cloned folder.

**Comment by synsin0** [comment]
I have implemented your code with no more errors. Thanks again for your answers and precious works. Please mark this issue as closed.

**Comment by ybarancan** [comment]
I am glad it worked out. 
Best
