### ISSUE TITLE
training speed

### ISSUE THREAD

**Issue by ShangWeize** [ybarancan/BEV_feat_stitch#8]
Hi, I found that the training speed with 1 GPU and 8 GPUs is about the same, about epoch every 7 minutes. And, I tried to make the batch_size larger, and the training speed did not improve. How can I set it up to speed up the training? Because I have been training more than 1000 epochs for more than 1 week.

**Comment by ybarancan** [comment]
You don't need to train 1000 epochs. We put an intentionally very high number to let the users decide when they want to stop. You can check the validation results to decide when to stop.
