### ISSUE TITLE
make_nuscenes_label.py failed

### ISSUE THREAD

**Issue by liuzhidemaomao** [ybarancan/BEV_feat_stitch#9]
Hello, when I tried to run make_nuscenes_labels.py, the ouput is like this:
![Mv2PMjzITk](https://user-images.githubusercontent.com/25152465/158748308-cfc1805a-8494-4074-a91e-9a7804b2cab0.png)
![NlTQdxLxzb](https://user-images.githubusercontent.com/25152465/158748332-eace8907-9ece-43c8-a339-4ea822f0cf11.png)
What is the matter with this, but the GT label seems OK?
![EX9HX3Rqaa](https://user-images.githubusercontent.com/25152465/158749014-edafdaad-786e-4762-8371-3b0436a239f5.png)

And also, the categories number in mine is different from [this one](https://github.com/ybarancan/BEV_feat_stitch/issues/4#issue-1140761825), which is 23 and mine is 32.

**Comment by ybarancan** [comment]
Hi,
The "error" messages are not actually error messages. They are just logging the currently processed scene name and token. In order to make sure that they will be printed, I set them to logging.error. So there is no problem. 
I don't know what exactly that image is. I assume it is non-decoded GT label. GT labels are encoded in PNG and it is use dafter decoding. So this looks very much normal to me. The black region is non-occluded, light gray is visible area and darker gray is visible AND non occluded. It will be much easier to see it when you look at the decoded labels.

You having different number of categories might have someting to do with your nuscenes version. Can you check if it is v1.0? If not, you can still try to run the code but I haven't tested it with other nuscenes versions so there might be problems.

**Comment by liuzhidemaomao** [comment]
> Hi, The "error" messages are not actually error messages. They are just logging the currently processed scene name and token. In order to make sure that they will be printed, I set them to logging.error. So there is no problem. I don't know what exactly that image is. I assume it is non-decoded GT label. GT labels are encoded in PNG and it is use dafter decoding. So this looks very much normal to me. The black region is non-occluded, light gray is visible area and darker gray is visible AND non occluded. It will be much easier to see it when you look at the decoded labels.
> 
> You having different number of categories might have someting to do with your nuscenes version. Can you check if it is v1.0? If not, you can still try to run the code but I haven't tested it with other nuscenes versions so there might be problems.

**Comment by liuzhidemaomao** [comment]
> 

Thank you for your generous reply. I have another question, the code used for generating NuScenes bev labels is similar to PON, but the number of labels is different. In PON, the number is 204895, yours is 34150.

**Comment by ybarancan** [comment]
That is not number of labels. The generation code is adopted from PON. We and PON use 14 classes (4 static and 10 object).

**Comment by liuzhidemaomao** [comment]
> That is not number of labels. The generation code is adopted from PON. We and PON use 14 classes (4 static and 10 object).

Sorry for the confusing formulation. The number here is the total number of .png files after running this code.

**Comment by ybarancan** [comment]
PON trains on all 6 cameras of the rig. We just use the front camera.

**Comment by liuzhidemaomao** [comment]
> 

Oh, I see. Thanks!

**Comment by Drchz155** [comment]
> 您好，当我尝试运行make_nuscenes_labels.py时，输出是这样的： ![Mv2PMjzITk](https://user-images.githubusercontent.com/25152465/158748308-cfc1805a-8494-4074-a91e-9a7804b2cab0.png) ![NlTQdxLxzb](https://user-images.githubusercontent.com/25152465/158748332-eace8907-9ece-43c8-a339-4ea822f0cf11.png)这是怎么回事，但 GT 标签似乎还可以？ ![EX9HX3Rqaa](https://user-images.githubusercontent.com/25152465/158749014-edafdaad-786e-4762-8371-3b0436a239f5.png)
> 
> 而且，我的类别编号与[这个](https://github.com/ybarancan/BEV_feat_stitch/issues/4#issue-1140761825)不同，它是 23，我的是 32。
**
**

**Comment by Drchz155** [comment]
> 嗨，“错误”消息实际上不是错误消息。它们只是记录当前处理的场景名称和令牌。为了确保它们将被打印出来，我将它们设置为 logging.error。所以没有问题。我不知道那个图像到底是什么。我假设它是未解码的 GT 标签。GT标签以PNG编码，并在解码后使用。所以这对我来说看起来很正常。黑色区域是非遮挡区域，浅灰色是可见区域，深灰色是可见且未遮挡的区域。当您查看解码的标签时，会更容易看到它。
> 
> 您拥有不同数量的类别可能与您的 nuscenes 版本有关。你能检查一下它是否是v1.0吗？如果没有，您仍然可以尝试运行代码，但我还没有使用其他 nuscenes 版本对其进行测试，因此可能会出现问题。

Thank you for your generous reply. How do I decode the ground truth image? I have obtained a similar GT image but I'm not sure if it's correct. Thank you very much.
